#Docker compose file
configserver:
  image: shreejejurkar/ConfigService
  ports:
   - "8888:8888"

accounts:
  image: shreejejurkar/AccountService
  links:
   - configserver
   
prices:
  image: shreejejurkar/PriceService
  links:
   - configserver

customers:
  image: shreejejurkar/CustomerService
  links:
   - configserver

stores:
  image: shreejejurkar/StoreService
  links:
   - configserver